### PR TITLE
fix: try to fix rultor config

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
try to fix rultor config

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by yegor256** [comment]
@volodya-lombrozo maybe this is the result of the recent changes we made in rultor?

**Comment by volodya-lombrozo** [comment]
@yegor256 It's impossible.
[The same fail](https://github.com/volodya-lombrozo/test-naming-conventions/pull/44#issuecomment-1408740325) with the same error - 2 days ago
[Recent changes](https://github.com/yegor256/rultor/pull/1578#issuecomment-1411969168) - 18 hours ago
[The same fail](https://github.com/volodya-lombrozo/test-naming-conventions/pull/44#issuecomment-1412243122) - 15 hour ago

I looks like our changes didn't applied.

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by yegor256** [comment]
@volodya-lombrozo try again

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Pull request merged**
