### PR TITLE
.rultor

### LINKED ISSUE #26: Add rultor support
It would be nice to add [rultor](https://www.rultor.com) support for the project.

### PR DESCRIPTION
**Pull request by l3r8yJ**
closes #26 
@volodya-lombrozo take a look, please

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@l3r8yJ Do you know whether `rultor` support of `GitHub` actions?
We actually already have deployment [pipeline](https://github.com/volodya-lombrozo/test-naming-conventions/blob/main/.github/workflows/maven.release.yml). Can we reuse it somehow?

**Comment by l3r8yJ** [comment]
@volodya-lombrozo I think not, I thought about that too, maybe @yegor256 can answer us

**Comment by volodya-lombrozo** [comment]
@l3r8yJ I've created the [issue](https://github.com/yegor256/rultor/issues/1565) in the Rultor project. Will see if it's possible.

**Comment by l3r8yJ** [comment]
@volodya-lombrozo for now, we can add it as a temporary `merge` and create a **new** issue. For example, `Fix rultor release` or something like that, and after refining [this issue] (https://github.com/yegor256/rultor/issues/1565) resolve it. What u think?

**Comment by volodya-lombrozo** [comment]
@l3r8yJ I think we can leave that PR as is. I would create a separate issue only for deploy phase.

**Review by volodya-lombrozo — APPROVED** [review]

**Pull request merged**
